// <auto-generated />
using System;
using APBD_Kolos2.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBD_Kolos2.Migrations
{
    [DbContext(typeof(CharacterDBContext))]
    partial class CharacterDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBD_Kolos2.Models.Backpacks", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("Backpacks");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            ItemId = 1,
                            Amount = 2
                        },
                        new
                        {
                            CharacterId = 1,
                            ItemId = 2,
                            Amount = 5
                        },
                        new
                        {
                            CharacterId = 1,
                            ItemId = 5,
                            Amount = 12
                        },
                        new
                        {
                            CharacterId = 1,
                            ItemId = 6,
                            Amount = 1
                        },
                        new
                        {
                            CharacterId = 2,
                            ItemId = 1,
                            Amount = 1
                        },
                        new
                        {
                            CharacterId = 2,
                            ItemId = 4,
                            Amount = 7
                        },
                        new
                        {
                            CharacterId = 2,
                            ItemId = 3,
                            Amount = 5
                        },
                        new
                        {
                            CharacterId = 3,
                            ItemId = 6,
                            Amount = 2
                        },
                        new
                        {
                            CharacterId = 3,
                            ItemId = 1,
                            Amount = 3
                        },
                        new
                        {
                            CharacterId = 3,
                            ItemId = 2,
                            Amount = 4
                        },
                        new
                        {
                            CharacterId = 3,
                            ItemId = 3,
                            Amount = 3
                        });
                });

            modelBuilder.Entity("APBD_Kolos2.Models.CharacterTitles", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CharacterId", "TitleId");

                    b.HasIndex("TitleId");

                    b.ToTable("CharacterTitles");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            TitleId = 3,
                            AcquiredAt = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CharacterId = 1,
                            TitleId = 5,
                            AcquiredAt = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CharacterId = 1,
                            TitleId = 2,
                            AcquiredAt = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CharacterId = 2,
                            TitleId = 1,
                            AcquiredAt = new DateTime(2022, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CharacterId = 2,
                            TitleId = 2,
                            AcquiredAt = new DateTime(2022, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CharacterId = 3,
                            TitleId = 4,
                            AcquiredAt = new DateTime(2021, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("APBD_Kolos2.Models.Characters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentWeight")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentWeight = 50,
                            FirstName = "Mariusz",
                            LastName = "Pudzianowski",
                            MaxWeight = 500
                        },
                        new
                        {
                            Id = 2,
                            CurrentWeight = 20,
                            FirstName = "Adam",
                            LastName = "Malysz",
                            MaxWeight = 180
                        },
                        new
                        {
                            Id = 3,
                            CurrentWeight = 35,
                            FirstName = "Krzysztof",
                            LastName = "Nowak",
                            MaxWeight = 120
                        });
                });

            modelBuilder.Entity("APBD_Kolos2.Models.Items", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Wielki Miecz",
                            Weight = 25
                        },
                        new
                        {
                            Id = 2,
                            Name = "Giga Kusza",
                            Weight = 10
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mikstura Zdrowia",
                            Weight = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Zapas Piwa",
                            Weight = 12
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mikstura Many",
                            Weight = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "Skorzana zbroja",
                            Weight = 12
                        });
                });

            modelBuilder.Entity("APBD_Kolos2.Models.Titles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Titles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pogrmoca Blokow"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wielki Czlowiek"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Najwiekszy z Polakow"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Zamieszkaly w domu"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Konsument Ryb"
                        });
                });

            modelBuilder.Entity("APBD_Kolos2.Models.Backpacks", b =>
                {
                    b.HasOne("APBD_Kolos2.Models.Characters", "Characters")
                        .WithMany("Backpacks")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_Kolos2.Models.Items", "Items")
                        .WithMany("Backpacks")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Characters");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("APBD_Kolos2.Models.CharacterTitles", b =>
                {
                    b.HasOne("APBD_Kolos2.Models.Characters", "Characters")
                        .WithMany("CharacterTitles")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_Kolos2.Models.Titles", "Titles")
                        .WithMany("CharacterTitles")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Characters");

                    b.Navigation("Titles");
                });

            modelBuilder.Entity("APBD_Kolos2.Models.Characters", b =>
                {
                    b.Navigation("Backpacks");

                    b.Navigation("CharacterTitles");
                });

            modelBuilder.Entity("APBD_Kolos2.Models.Items", b =>
                {
                    b.Navigation("Backpacks");
                });

            modelBuilder.Entity("APBD_Kolos2.Models.Titles", b =>
                {
                    b.Navigation("CharacterTitles");
                });
#pragma warning restore 612, 618
        }
    }
}
